name: Lint and Test

on:
  # manual trigger
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: yarn lint

  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: actions/cache@v3
        id: cypress-cache
        with:
          path: /home/runner/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('node_modules/cypress') }}
      - if: steps.cypress-cache.outputs.cache-hit != 'true'
        run: yarn cypress install
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          install: false
          browser: chrome
          start: yarn start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
